ARDUINO_DIR = /Applications/Arduino.app/Contents/Resources/Java
                                            
TARGET       = motortest
#MCU          = atmega328p
MCU          = atmega168
F_CPU        = 16000000

ARDUINO_PORT = /dev/cu.usb*
#AVRDUDE_ARD_BAUDRATE = 57600
AVRDUDE_ARD_BAUDRATE = 19200
                                            
include ../arduino-mk/Arduino.mk
